server:
  port: 8086

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/payment_service_db
    username: halalbiteuser
    password: halalbitepass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      write-dates-as-timestamps: false

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

# Stripe configuration
# Replace with real keys from dashboard.stripe.com
# Leave as-is to use simulation mode (no real Stripe needed)
paypal:
  client-id: 'AeFri9XLazx-1X5dJ1eBOctKJqVzQMd_RRkuCTBhy2jnvV2AvESgR_Fz8Z__M6VxS9r8e00_8kXHifU6'
  client-secret: 'ELuq6tKtK6eX-7VtdHaY107jfbXRKW6w0QfSJCSBbzTQRZqq7QJ4SKbMDvrS-GtdpCN-o-AZZrbSlbOv'
  mode: sandbox
  base-url: https://api-m.sandbox.paypal.com

jwt:
  secret: halal-bite-super-secret-jwt-key-2026-production

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.halalbite.paymentservice: DEBUG
    org.springframework.kafka: INFO

# Frontend URL for PayPal redirect
app:
  frontend-url: http://localhost:8088