server:
  port: 8080

spring:
  application:
    name: api-gateway


  jackson:
    serialization:
      write-dates-as-timestamps: false


  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/api/v1/restaurants/**

        - id: menu-service
          uri: lb://menu-service
          predicates:
            - Path=/api/v1/menus/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**

        - id: service-registry
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

      default-filters:
        - AddRequestHeader=X-Halalbite-Request-Source, api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

jwt:
  secret: halal-bite-super-secret-jwt-key-2026-production

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.halalbite.apigateway: DEBUG
